
skillMetadata:
  sections:
    - name: Audio File Path
      fields:
        - name: audio_file_path
          type: text
          label: Audio File Path
          value: ""
          placeholder: URL for audio file.
