
skillMetadata:
  sections:
    - name: MP3 URL
      fields:
        - name: audio_file_path
          type: text
          label: MP3 URL
          value: ""
          placeholder: MP3 URL for audio file.
